### ISSUE TITLE
how do you update path for execute("jar -xf #{installer_path} #{init_script}")

### ISSUE THREAD

**Issue by JaminShanti** [Dynatrace/Dynatrace-AppMon-Puppet#29]
for provider dynatrace_installation, where do you define path for execute("jar -xf #{installer_path} #{init_script}")

**Comment by jkulesz** [comment]
It is created dynamically in .../dynatrace/lib/puppet/provider/dynatrace_installer.rb from installer_cache_dir and installer_file_name.
