### ISSUE TITLE
Quiet down the dynatrace_installation provider

### ISSUE THREAD

**Issue by MG2R** [Dynatrace/Dynatrace-AppMon-Puppet#33]
Right now there are a lot of `puts`s in the [dynactrace_installation provider](https://github.com/Dynatrace/Dynatrace-Puppet/blob/53a7247a91a367ba6e93b990bcfae2563475702c/lib/puppet/provider/dynatrace_installation/ruby.rb). Unless I'm missing something obvious these seem to be for debugging purposes. Can these be removed or somehow only be shown when puppet is run in debug mode?

The specific line I'm seeing on my systems is:

```
Checking if requires installation for path: /opt/dynatrace-6.3/agent. Result: false, ensure= present
```

**Comment by MarcinZejer** [comment]
Thanks for your remarks but we think it is a good option to display more than less. However we will think about refactoring in the future.
